---

- name: nginx
  hosts: all
  become: yes

  tasks:
    - name: Update & Upgrade system
      apt:
       update_cache: yes
       upgrade: dist

    - name: Install Certbot
      apt:
       name: 
         - certbot
         - python3-certbot-nginx
       state: present
    
    - name: Obtain SSL certificate
      shell: certbot --nginx --agree-tos --redirect --email {{ email }} -d {{ domain }}

    - name: Configure Certbot autorenewal
      shell: certbot renew --dry-run
      register: result_renewal

    - name: Show output renewal SSL
      ansible.builtin.debug:
        msg: "{{ result_renewal.changed }}"
