---
- name: Uninstall Nginx
  hosts: all
  become: yes
  
  tasks:
    - name: Ensure nginx is not installed
      apt: 
        name: nginx
        state: absent
        purge: yes
        autoremove: yes

    - name: Ensure nginx-common is not installed
      apt: 
        name: nginx-common
        state: absent
        purge: yes
        autoremove: yes
        
    - name: Stop nginx
      service:
          name: nginx
          state: stopped