---
- name: Uninstall Nginx
  hosts: all
  become: yes
  
  tasks:
    - name: ensure nginx is not installed
      apt: 
        name: nginx 
        state: absent
        autoremove: yes
        
    - name: stop nginx
      service:
          name: nginx
          state: stopped