---

- name: nginx
  hosts: all
  become: yes

  tasks:
    - name: Update & Upgrade system
      apt:
       update_cache: yes
       upgrade: dist

    - name: Install Certbot
      apt:
       name: 
         - certbot
         - python3-certbot-apache
       state: present
    
    - name: Obtain SSL certificate
      shell: certbot --apache --agree-tos --redirect --email {{ email }} -d {{ domain }}
      args:
        executable: /bin/bash
      notify: restart apache2

    - name: Configure Certbot autorenewal
      shell: certbot renew --dry-run
      notify: restart apache2
      register: result_renewal

    - name: Show output renewal SSL
      ansible.builtin.debug:
        msg: "{{ result_renewal.changed }}"

  handlers:
    - name: restart apache2
      ansible.builtin.service:
        name: apache2
        state: restarted